language: node_js
node_js:
- 16.13.1
branches:
  only:
  - master
cache: yarn
addons:
  ssh_known_hosts:
  - 101.35.190.75
install:
- yarn
script:
- yarn build
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
# - chmod 600 .ssh/authorized_keys
# - ssh-add .ssh/authorized_keys
after_success:
- rsync -az --delete ./dist/* root@101.35.190.75:/home/nginx/www/qx-admin