language: node_js
node_js:
- 16.13.1
branches:
  only:
  - master
cache:
  apt: true
  yarn: true
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 101.35.190.75
install:
- yarn
script:
- yarn build
before_install:
- openssl aes-256-cbc -K $encrypted_0894cc22e6b1_key -iv $encrypted_0894cc22e6b1_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 101.35.190.75\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- rsync -az --delete ./dist/* root@101.35.190.75:/home/nginx/www/qx-admin
